-- Get the column information for the specified table
SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    CASE WHEN IS_NULLABLE = 'YES' THEN 'DEFAULT NULL' ELSE 'NOT NULL' END AS IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'hbtn_0c_0'
AND TABLE_NAME = 'first_table';



